
-- SHIFT + ALT + I (PARA ATIVAR O CURSOR EM MULTIPLAS LINHAS SELECIONADAS)

WITH tb_cand AS (

    SELECT 
        SQ_CANDIDATO,
        SG_UF,
        DS_CARGO,
        SG_PARTIDO,
        NM_PARTIDO,
        DT_NASCIMENTO,
        DS_GENERO,
        DS_GRAU_INSTRUCAO,
        DS_ESTADO_CIVIL,
        DS_COR_RACA,      
        DS_OCUPACAO
    FROM tb_candidaturas

),

tb_total_bens AS (

    SELECT
        SQ_CANDIDATO,
        SUM(CAST(REPLACE(VR_BEM_CANDIDATO, ',', '.') AS DECIMAL(15,2))) AS TOTAL_BENS
    FROM tb_bens
    GROUP BY 1

),

tb_info_completa_cand AS (

    SELECT 
        t1.*,
        COALESCE(t2.TOTAL_BENS, 0) AS TOTAL_BENS
    FROM tb_cand AS t1
    LEFT JOIN tb_total_bens AS t2
    ON t1.SQ_CANDIDATO = t2.SQ_CANDIDATO

),

tb_group_uf AS (

    SELECT  
        SG_PARTIDO,
        NM_PARTIDO,
        SG_UF,
        AVG(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TX_GEN_FEMININO,
        SUM(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TOTAL_GEN_FEMININO,
        AVG(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA,
        SUM(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA,
        AVG(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA_PARDA,
        SUM(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA_PARDA,
        AVG(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA,
        SUM(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_NAO_BRANCA,
        COUNT(*) AS TOTAL_CANDIDATURAS

    FROM tb_info_completa_cand
    GROUP BY 1, 2, 3
),
 

tb_group_br AS (

SELECT 
    SG_PARTIDO,
    NM_PARTIDO,
    'BR' AS SG_UF,
    1.0 * SUM(TOTAL_GEN_FEMININO) / SUM(TOTAL_CANDIDATURAS) AS TX_GEN_FEMININO,
    SUM(TOTAL_GEN_FEMININO) AS TOTAL_GEN_FEMININO,

    1.0 * SUM(TOTAL_COR_RACA_PRETA) / SUM(TOTAL_CANDIDATURAS) AS TX_COR_RACA_PRETA,
    SUM(TOTAL_COR_RACA_PRETA) AS TOTAL_COR_RACA_PRETA,

    1.0 * SUM(TOTAL_COR_RACA_PRETA_PARDA) / SUM(TOTAL_CANDIDATURAS) AS TX_COR_RACA_PRETA_PARDA,
    SUM(TOTAL_COR_RACA_PRETA_PARDA) AS TOTAL_COR_RACA_PRETA_PARDA,

    1.0 * SUM(TOTAL_COR_RACA_NAO_BRANCA) / SUM(TOTAL_CANDIDATURAS) AS TX_COR_RACA_NAO_BRANCA,
    SUM(TOTAL_COR_RACA_NAO_BRANCA) AS TOTAL_COR_RACA_NAO_BRANCA,

    SUM(TOTAL_CANDIDATURAS) AS TOTAL_CANDIDATURAS

FROM tb_group_uf

GROUP BY 1,2,3
),

tb_union_all AS (

    SELECT * FROM tb_group_br

    UNION ALL

    SELECT * FROM tb_group_uf
)

SELECT * FROM tb_union_all

