
-- SHIFT + ALT + I (PARA ATIVAR O CURSOR EM MULTIPLAS LINHAS SELECIONADAS)

WITH tb_cand AS (

    SELECT
        SQ_CANDIDATO,
        SG_UF,
        DS_CARGO,
        SG_PARTIDO,
        NM_PARTIDO,
        DT_NASCIMENTO,
        DS_GENERO,
        DS_GRAU_INSTRUCAO,
        DS_ESTADO_CIVIL,
        DS_COR_RACA,      
        DS_OCUPACAO
    FROM tb_candidaturas

),

tb_total_bens AS (

    SELECT
        SQ_CANDIDATO,
        SUM(CAST(REPLACE(VR_BEM_CANDIDATO, ',', '.') AS DECIMAL(15,2))) AS TOTAL_BENS
    FROM tb_bens
    GROUP BY 1

),

tb_info_completa_cand AS (

    SELECT 
        t1.*,
        COALESCE(t2.TOTAL_BENS, 0) AS TOTAL_BENS
    FROM tb_cand AS t1
    LEFT JOIN tb_total_bens AS t2
    ON t1.SQ_CANDIDATO = t2.SQ_CANDIDATO

),

tb_group_uf AS (

    SELECT  
        SG_PARTIDO,
        NM_PARTIDO,
        'GERAL' AS DS_CARGO,
        SG_UF,
        AVG(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TX_GEN_FEMININO,
        SUM(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TOTAL_GEN_FEMININO,
        AVG(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA,
        SUM(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA,
        AVG(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA_PARDA,
        SUM(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA_PARDA,
        AVG(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA,
        SUM(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_NAO_BRANCA,
        COUNT(*) AS TOTAL_CANDIDATURAS

    FROM tb_info_completa_cand
    GROUP BY 1,2,3,4
),
 

tb_group_br AS (

    SELECT  
        SG_PARTIDO,
        NM_PARTIDO,
        'GERAL' AS DS_CARGO,
        'BR' AS SG_UF,
        AVG(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TX_GEN_FEMININO,
        SUM(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TOTAL_GEN_FEMININO,
        AVG(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA,
        SUM(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA,
        AVG(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA_PARDA,
        SUM(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA_PARDA,
        AVG(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA,
        SUM(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_NAO_BRANCA,
        COUNT(*) AS TOTAL_CANDIDATURAS

    FROM tb_info_completa_cand
    GROUP BY 1,2,3,4

),

tb_group_cargo_uf AS (
    
    SELECT  
        SG_PARTIDO,
        NM_PARTIDO,
        DS_CARGO,
        SG_UF,
        AVG(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TX_GEN_FEMININO,
        SUM(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TOTAL_GEN_FEMININO,
        AVG(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA,
        SUM(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA,
        AVG(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA_PARDA,
        SUM(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA_PARDA,
        AVG(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA,
        SUM(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_NAO_BRANCA,
        COUNT(*) AS TOTAL_CANDIDATURAS

    FROM tb_info_completa_cand AS t1
    GROUP BY 1,2,3,4
),

tb_group_cargo_br AS (
    
    SELECT  
        SG_PARTIDO,
        NM_PARTIDO,
        DS_CARGO,
        'BR' AS SG_UF,
        AVG(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TX_GEN_FEMININO,
        SUM(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TOTAL_GEN_FEMININO,
        AVG(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA,
        SUM(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA,
        AVG(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA_PARDA,
        SUM(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA_PARDA,
        AVG(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA,
        SUM(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_NAO_BRANCA,
        COUNT(*) AS TOTAL_CANDIDATURAS

    FROM tb_info_completa_cand AS t1
    GROUP BY 1,2,3,4
),

tb_union_all AS (

    SELECT * FROM tb_group_uf

    UNION ALL

    SELECT * FROM tb_group_br

    UNION ALL

    SELECT * FROM tb_group_cargo_uf

    UNION ALL

    SELECT * FROM tb_group_cargo_br
)

SELECT * FROM tb_union_all