
-- SHIFT + ALT + I (PARA ATIVAR O CURSOR EM MULTIPLAS LINHAS SELECIONADAS)

WITH tb_cand AS (

    SELECT 
        SQ_CANDIDATO,
        SG_UF,
        DS_CARGO,
        SG_PARTIDO,
        NM_PARTIDO,
        DT_NASCIMENTO,
        DS_GENERO,
        DS_GRAU_INSTRUCAO,
        DS_ESTADO_CIVIL,
        DS_COR_RACA,      
        DS_OCUPACAO
    FROM tb_candidaturas

),

tb_total_bens AS (

    SELECT
        SQ_CANDIDATO,
        SUM(CAST(REPLACE(VR_BEM_CANDIDATO, ',', '.') AS DECIMAL(15,2))) AS TOTAL_BENS
    FROM tb_bens
    GROUP BY 1

),

tb_info_completa_cand AS (

    SELECT 
        t1.*,
        COALESCE(t2.TOTAL_BENS, 0) AS TOTAL_BENS
    FROM tb_cand AS t1
    LEFT JOIN tb_total_bens AS t2
    ON t1.SQ_CANDIDATO = t2.SQ_CANDIDATO

),

tb_group_uf AS (

    SELECT  
        SG_PARTIDO,
        NM_PARTIDO,
        SG_UF,
        AVG(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TX_GEN_FEMININO,
        SUM(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS TOTAL_GEN_FEMININO,
        AVG(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA,
        SUM(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA,
        AVG(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TX_COR_RACA_PRETA_PARDA,
        SUM(CASE WHEN DS_COR_RACA IN ('PRETA','PARDA') THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_PRETA_PARDA,
        AVG(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA,
        SUM(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS TOTAL_COR_RACA_NAO_BRANCA,
        COUNT(*) AS TOTAL_CANDIDATURAS

    FROM tb_info_completa_cand
    GROUP BY 1, 2, 3
),
 
tb_all AS (

    SELECT

        SG_PARTIDO,
        NM_PARTIDO,
        SUM(CASE WHEN SG_UF = 'AC' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_AC,
        SUM(CASE WHEN SG_UF = 'AL' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_AL,
        SUM(CASE WHEN SG_UF = 'AM' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_AM,
        SUM(CASE WHEN SG_UF = 'AP' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_AP,
        SUM(CASE WHEN SG_UF = 'BA' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_BA,
        SUM(CASE WHEN SG_UF = 'CE' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_CE,
        SUM(CASE WHEN SG_UF = 'ES' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_ES,
        SUM(CASE WHEN SG_UF = 'GO' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_GO,
        SUM(CASE WHEN SG_UF = 'MA' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_MA,
        SUM(CASE WHEN SG_UF = 'MG' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_MG,
        SUM(CASE WHEN SG_UF = 'MS' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_MS,
        SUM(CASE WHEN SG_UF = 'MT' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_MT,
        SUM(CASE WHEN SG_UF = 'PA' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_PA,
        SUM(CASE WHEN SG_UF = 'PB' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_PB,
        SUM(CASE WHEN SG_UF = 'PE' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_PE,
        SUM(CASE WHEN SG_UF = 'PI' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_PI,
        SUM(CASE WHEN SG_UF = 'PR' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_PR,
        SUM(CASE WHEN SG_UF = 'RJ' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_RJ,
        SUM(CASE WHEN SG_UF = 'RN' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_RN,
        SUM(CASE WHEN SG_UF = 'RO' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_RO,
        SUM(CASE WHEN SG_UF = 'RR' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_RR,
        SUM(CASE WHEN SG_UF = 'RS' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_RS,
        SUM(CASE WHEN SG_UF = 'SC' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_SC,
        SUM(CASE WHEN SG_UF = 'SE' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_SE,
        SUM(CASE WHEN SG_UF = 'SP' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_SP,
        SUM(CASE WHEN SG_UF = 'TO' THEN TX_GEN_FEMININO ELSE 0 END) AS TX_GEN_FEM_TO,
        1.0 * SUM(TOTAL_GEN_FEMININO) / SUM(TOTAL_CANDIDATURAS) AS TX_GEN_FEM_BR,

        SUM(CASE WHEN SG_UF = 'AC' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_AC,
        SUM(CASE WHEN SG_UF = 'AL' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_AL,
        SUM(CASE WHEN SG_UF = 'AM' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_AM,
        SUM(CASE WHEN SG_UF = 'AP' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_AP,
        SUM(CASE WHEN SG_UF = 'BA' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_BA,
        SUM(CASE WHEN SG_UF = 'CE' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_CE,
        SUM(CASE WHEN SG_UF = 'ES' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_ES,
        SUM(CASE WHEN SG_UF = 'GO' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_GO,
        SUM(CASE WHEN SG_UF = 'MA' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_MA,
        SUM(CASE WHEN SG_UF = 'MG' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_MG,
        SUM(CASE WHEN SG_UF = 'MS' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_MS,
        SUM(CASE WHEN SG_UF = 'MT' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_MT,
        SUM(CASE WHEN SG_UF = 'PA' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_PA,
        SUM(CASE WHEN SG_UF = 'PB' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_PB,
        SUM(CASE WHEN SG_UF = 'PE' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_PE,
        SUM(CASE WHEN SG_UF = 'PI' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_PI,
        SUM(CASE WHEN SG_UF = 'PR' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_PR,
        SUM(CASE WHEN SG_UF = 'RJ' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_RJ,
        SUM(CASE WHEN SG_UF = 'RN' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_RN,
        SUM(CASE WHEN SG_UF = 'RO' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_RO,
        SUM(CASE WHEN SG_UF = 'RR' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_RR,
        SUM(CASE WHEN SG_UF = 'RS' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_RS,
        SUM(CASE WHEN SG_UF = 'SC' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_SC,
        SUM(CASE WHEN SG_UF = 'SE' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_SE,
        SUM(CASE WHEN SG_UF = 'SP' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_SP,
        SUM(CASE WHEN SG_UF = 'TO' THEN TX_COR_RACA_PRETA ELSE 0 END) AS TX_COR_RACA_PRETA_TO,
        1.0 * SUM(TOTAL_COR_RACA_PRETA) / SUM(TOTAL_CANDIDATURAS) AS TX_COR_RACA_PRETA_BR,

        SUM(CASE WHEN SG_UF = 'AC' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_AC,
        SUM(CASE WHEN SG_UF = 'AL' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_AL,
        SUM(CASE WHEN SG_UF = 'AM' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_AM,
        SUM(CASE WHEN SG_UF = 'AP' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_AP,
        SUM(CASE WHEN SG_UF = 'BA' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_BA,
        SUM(CASE WHEN SG_UF = 'CE' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_CE,
        SUM(CASE WHEN SG_UF = 'ES' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_ES,
        SUM(CASE WHEN SG_UF = 'GO' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_GO,
        SUM(CASE WHEN SG_UF = 'MA' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_MA,
        SUM(CASE WHEN SG_UF = 'MG' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_MG,
        SUM(CASE WHEN SG_UF = 'MS' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_MS,
        SUM(CASE WHEN SG_UF = 'MT' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_MT,
        SUM(CASE WHEN SG_UF = 'PA' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_PA,
        SUM(CASE WHEN SG_UF = 'PB' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_PB,
        SUM(CASE WHEN SG_UF = 'PE' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_PE,
        SUM(CASE WHEN SG_UF = 'PI' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_PI,
        SUM(CASE WHEN SG_UF = 'PR' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_PR,
        SUM(CASE WHEN SG_UF = 'RJ' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_RJ,
        SUM(CASE WHEN SG_UF = 'RN' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_RN,
        SUM(CASE WHEN SG_UF = 'RO' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_RO,
        SUM(CASE WHEN SG_UF = 'RR' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_RR,
        SUM(CASE WHEN SG_UF = 'RS' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_RS,
        SUM(CASE WHEN SG_UF = 'SC' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_SC,
        SUM(CASE WHEN SG_UF = 'SE' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_SE,
        SUM(CASE WHEN SG_UF = 'SP' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_SP,
        SUM(CASE WHEN SG_UF = 'TO' THEN TX_COR_RACA_NAO_BRANCA ELSE 0 END) AS TX_COR_RACA_NAO_BRANCA_TO,
        1.0 * SUM(TOTAL_COR_RACA_NAO_BRANCA) / SUM(TOTAL_CANDIDATURAS) AS TX_COR_RACA_NAO_BRANCA_BR,

        SUM(CASE WHEN SG_UF = 'AC' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_AC,
        SUM(CASE WHEN SG_UF = 'AL' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_AL,
        SUM(CASE WHEN SG_UF = 'AM' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_AM,
        SUM(CASE WHEN SG_UF = 'AP' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_AP,
        SUM(CASE WHEN SG_UF = 'BA' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_BA,
        SUM(CASE WHEN SG_UF = 'CE' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_CE,
        SUM(CASE WHEN SG_UF = 'ES' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_ES,
        SUM(CASE WHEN SG_UF = 'GO' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_GO,
        SUM(CASE WHEN SG_UF = 'MA' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_MA,
        SUM(CASE WHEN SG_UF = 'MG' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_MG,
        SUM(CASE WHEN SG_UF = 'MS' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_MS,
        SUM(CASE WHEN SG_UF = 'MT' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_MT,
        SUM(CASE WHEN SG_UF = 'PA' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_PA,
        SUM(CASE WHEN SG_UF = 'PB' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_PB,
        SUM(CASE WHEN SG_UF = 'PE' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_PE,
        SUM(CASE WHEN SG_UF = 'PI' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_PI,
        SUM(CASE WHEN SG_UF = 'PR' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_PR,
        SUM(CASE WHEN SG_UF = 'RJ' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_RJ,
        SUM(CASE WHEN SG_UF = 'RN' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_RN,
        SUM(CASE WHEN SG_UF = 'RO' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_RO,
        SUM(CASE WHEN SG_UF = 'RR' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_RR,
        SUM(CASE WHEN SG_UF = 'RS' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_RS,
        SUM(CASE WHEN SG_UF = 'SC' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_SC,
        SUM(CASE WHEN SG_UF = 'SE' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_SE,
        SUM(CASE WHEN SG_UF = 'SP' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_SP,
        SUM(CASE WHEN SG_UF = 'TO' THEN TX_COR_RACA_PRETA_PARDA ELSE 0 END) AS TX_COR_RACA_PRETOS_PARDOS_TO,
        1.0 * SUM(TOTAL_COR_RACA_PRETA_PARDA) / SUM(TOTAL_CANDIDATURAS) AS TX_COR_RACA_PRETA_PARDA_BR,

        SUM(TOTAL_GEN_FEMININO) AS TOTAL_GEN_FEMININO,
        SUM(TOTAL_COR_RACA_PRETA) AS TOTAL_COR_RACA_PRETA,
        SUM(TOTAL_COR_RACA_NAO_BRANCA) AS TOTAL_COR_RACA_NAO_BRANCA,
        SUM(TOTAL_COR_RACA_PRETA_PARDA) AS TOTAL_COR_RACA_PRETA_PARDA,
        SUM(TOTAL_CANDIDATURAS) AS TOTAL_CANDIDATURAS

    FROM tb_group_uf

    GROUP BY 1, 2
)

SELECT * FROM tb_all

